import { supabase, supabaseConfigured, getCurrentProfile } from './supabase.js';

const STORAGE='tnps-erp-v2';
let syncTimer=null,syncing=false,installed=false,lastSnapshot=null,nativeSet=null;
const studentFromDb=s=>({id:s.student_id,admissionNo:s.admission_number,name:s.name,father:s.father_name||s.guardian_name||'',phone:s.parent_phone||'',className:s.class_name||'',section:s.section||'',dob:s.dob||'',gender:s.gender||'',home:s.home_address||'',homeMaps:s.home_location_url||'',photo:s.photo_url||'',aadhaar:s.aadhaar_number||'',documents:[]});
const teacherFromDb=t=>({id:t.teacher_id,name:t.name,phone:t.phone||'',email:t.email||'',designation:t.designation||'Teacher',qualification:t.qualification||'',className:t.class_name||'',subjects:t.subjects||'',joining:t.joining_date||'',photo:t.photo_url||'',documents:[]});
const attendanceFromDb=(a,students,teachers)=>{const p=a.kind==='student'?students.find(s=>s.id===a.student_id):teachers.find(t=>t.id===a.teacher_id);return{id:p?.id||a.id,kind:a.kind,name:p?.name||'Unknown',date:a.attendance_date,time:a.attendance_time?new Date(a.attendance_time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'',status:a.status||'present',timestamp:a.attendance_time||null,className:p?.className||''};};
export async function loadDatabase(){if(!supabaseConfigured)return false;const{data:{user}}=await supabase.auth.getUser();if(!user)return false;const{profile}=await getCurrentProfile();if(!profile?.active)return false;const[sr,tr,ar,tt,hw,no,ex]=await Promise.all([supabase.from('students').select('student_id,admission_number,name,father_name,guardian_name,parent_phone,class_name,section,dob,gender,home_address,home_location_url,photo_url,aadhaar_number').eq('active',true).order('name'),supabase.from('teachers').select('teacher_id,name,phone,email,designation,qualification,class_name,subjects,joining_date,photo_url').eq('active',true).order('name'),supabase.from('attendance').select('id,attendance_date,attendance_time,kind,status,student_id,teacher_id').order('attendance_date',{ascending:false}).order('attendance_time',{ascending:false}),supabase.from('timetable').select('*').order('day_of_week').order('start_time'),supabase.from('homework').select('*').order('due_date',{ascending:false}),supabase.from('notices').select('*').order('published_at',{ascending:false}),supabase.from('exams').select('*').order('exam_date',{ascending:false})]);const failed=[sr,tr,ar,tt,hw,no,ex].find(r=>r.error);if(failed){console.error('[TNPS] Database load failed',failed.error);return false;}const students=(sr.data||[]).map(studentFromDb),teachers=(tr.data||[]).map(teacherFromDb),attendance=(ar.data||[]).map(a=>attendanceFromDb(a,sr.data||[],tr.data||[]));const current=JSON.parse(window.localStorage.getItem(STORAGE)||'{}');const next={...current,students,teachers,attendance,timetable:tt.data||[],homework:hw.data||[],notices:no.data||[],exams:ex.data||[],_databaseConnected:true,_profileRole:profile.role,_profileId:profile.id};nativeSet(STORAGE,JSON.stringify(next));lastSnapshot=next;return true;}
async function syncStudents(list){if(!Array.isArray(list)||!list.length)return;const rows=list.map(s=>({student_id:s.id,admission_number:s.admissionNo,name:s.name,father_name:s.father||null,parent_phone:s.phone||null,class_name:s.className||null,section:s.section||null,dob:s.dob||null,gender:s.gender||null,home_address:s.home||null,home_location_url:s.homeMaps||null,photo_url:s.photo||null,aadhaar_number:s.aadhaar||null,active:s.active??true}));const{error}=await supabase.from('students').upsert(rows,{onConflict:'student_id'});if(error)console.error('[TNPS] Student sync failed',error);}
async function syncTeachers(list){if(!Array.isArray(list)||!list.length)return;const rows=list.map(t=>({teacher_id:t.id,name:t.name,phone:t.phone||null,email:t.email||null,designation:t.designation||'Teacher',qualification:t.qualification||null,joining_date:t.joining||null,class_name:t.className||null,subjects:t.subjects||null,photo_url:t.photo||null,active:t.active??true}));const{error}=await supabase.from('teachers').upsert(rows,{onConflict:'teacher_id'});if(error)console.error('[TNPS] Teacher sync failed',error);}
async function syncAttendance(list){if(!Array.isArray(list)||!list.length)return;const[{data:students},{data:teachers}]=await Promise.all([supabase.from('students').select('id,student_id'),supabase.from('teachers').select('id,teacher_id')]);const sm=new Map((students||[]).map(x=>[x.student_id,x.id])),tm=new Map((teachers||[]).map(x=>[x.teacher_id,x.id]));for(const item of list){const personId=item.kind==='student'?sm.get(item.id):tm.get(item.id);if(!personId)continue;const{error}=await supabase.rpc('record_attendance',{person_id:personId,person_type:item.kind,scanned_token:item.id});if(error&&!/already_marked_today|duplicate/i.test(String(error.message||'')))console.error('[TNPS] Attendance sync failed',error.message);}}
function scheduleSync(changes){if(syncTimer)clearTimeout(syncTimer);if(!changes.students&&!changes.teachers&&!changes.attendance)return;syncTimer=setTimeout(()=>syncPatch(changes),450)}
async function syncPatch(changes){if(!supabaseConfigured||syncing)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;syncing=true;try{if(changes.students)await syncStudents(changes.students);if(changes.teachers)await syncTeachers(changes.teachers);if(changes.attendance)await syncAttendance(changes.attendance);}finally{syncing=false;}}
export async function initDatabaseBridge(){if(!supabaseConfigured)return{connected:false,authenticated:false};nativeSet=Storage.prototype.setItem.bind(window.localStorage);if(!installed){const native=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){native.call(this,key,value);if(key!==STORAGE)return;try{const next=JSON.parse(value),previous=lastSnapshot||JSON.parse(window.localStorage.getItem(STORAGE)||'{}'),changes={};if(JSON.stringify(previous.students||[])!==JSON.stringify(next.students||[]))changes.students=next.students||[];if(JSON.stringify(previous.teachers||[])!==JSON.stringify(next.teachers||[]))changes.teachers=next.teachers||[];const previousAttendance=previous.attendance||[],nextAttendance=next.attendance||[];if(nextAttendance.length>previousAttendance.length)changes.attendance=nextAttendance.slice(previousAttendance.length);lastSnapshot=next;scheduleSync(changes);}catch{}};installed=true;}const connected=await loadDatabase();supabase.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session){const ok=await loadDatabase();window.dispatchEvent(new CustomEvent('tnps-database-ready',{detail:{connected:ok,authenticated:ok}}));}if(event==='SIGNED_OUT'){nativeSet(STORAGE,JSON.stringify({students:[],teachers:[],attendance:[],exams:[],results:[],timetable:[],notices:[],homework:[],printed:[]}));lastSnapshot=null;}});return{connected,authenticated:connected};}
