import { supabase, supabaseConfigured, getCurrentProfile } from './supabase.js';

const STORAGE = 'tnps-erp-v2';
const studentFromDb = s => ({id:s.student_id,admissionNo:s.admission_number,name:s.name,father:s.father_name||s.guardian_name||'',phone:s.parent_phone||'',className:s.class_name||'',section:s.section||'',dob:s.dob||'',gender:s.gender||'',home:s.home_address||'',homeMaps:s.home_location_url||'',photo:s.photo_url||'',aadhaar:s.aadhaar_number||'',documents:[]});
const teacherFromDb = t => ({id:t.teacher_id,name:t.name,phone:t.phone||'',email:t.email||'',designation:t.designation||'Teacher',qualification:t.qualification||'',className:t.class_name||'',subjects:t.subjects||'',joining:t.joining_date||'',photo:t.photo_url||'',documents:[]});
const attendanceFromDb = (a,students,teachers) => {const p=a.kind==='student'?students.find(s=>s.id===a.student_id):teachers.find(t=>t.id===a.teacher_id);return{id:p?.id||a.id,kind:a.kind,name:p?.name||'Unknown',date:a.attendance_date,time:a.attendance_time?new Date(a.attendance_time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'',status:a.status||'present',timestamp:a.attendance_time||null};};
export async function loadDatabase(){if(!supabaseConfigured)return false;const{data:{user}}=await supabase.auth.getUser();if(!user)return false;const{profile}=await getCurrentProfile();if(!profile?.active)return false;const[sr,tr,ar,tt,hw,no,ex]=await Promise.all([supabase.from('students').select('*').eq('active',true).order('name'),supabase.from('teachers').select('*').eq('active',true).order('name'),supabase.from('attendance').select('*').order('attendance_date',{ascending:false}).order('attendance_time',{ascending:false}),supabase.from('timetable').select('*').order('day_of_week').order('start_time'),supabase.from('homework').select('*').order('due_date',{ascending:false}),supabase.from('notices').select('*').order('published_at',{ascending:false}),supabase.from('exams').select('*').order('exam_date',{ascending:false})]);const failed=[sr,tr,ar,tt,hw,no,ex].find(r=>r.error);if(failed){console.error('TNPS database load failed',failed.error);return false;}const students=(sr.data||[]).map(studentFromDb),teachers=(tr.data||[]).map(teacherFromDb),attendance=(ar.data||[]).map(a=>attendanceFromDb(a,sr.data||[],tr.data||[])),current=JSON.parse(window.localStorage.getItem(STORAGE)||'{}');window.localStorage.setItem(STORAGE,JSON.stringify({...current,students,teachers,attendance,timetable:tt.data||[],homework:hw.data||[],notices:no.data||[],exams:ex.data||[],_databaseConnected:true,_profileRole:profile.role,_profileId:profile.id}));return true;}
async function syncStudents(list){if(!Array.isArray(list)||!list.length)return;const rows=list.map(s=>({student_id:s.id,admission_number:s.admissionNo,name:s.name,father_name:s.father||null,guardian_name:s.guardian_name||null,parent_phone:s.phone||null,class_name:s.className||null,section:s.section||null,dob:s.dob||null,gender:s.gender||null,home_address:s.home||null,home_location_url:s.homeMaps||null,photo_url:s.photo||null,aadhaar_number:s.aadhaar||null,active:s.active??true}));const{error}=await supabase.from('students').upsert(rows,{onConflict:'student_id'});if(error)console.error('Student sync failed',error);}
async function syncTeachers(list){if(!Array.isArray(list)||!list.length)return;const rows=list.map(t=>({teacher_id:t.id,name:t.name,phone:t.phone||null,email:t.email||null,designation:t.designation||'Teacher',qualification:t.qualification||null,joining_date:t.joining||null,class_name:t.className||null,subjects:t.subjects||null,photo_url:t.photo||null,active:t.active??true}));const{error}=await supabase.from('teachers').upsert(rows,{onConflict:'teacher_id'});if(error)console.error('Teacher sync failed',error);}
async function syncAttendance(list){if(!Array.isArray(list)||!list.length)return;const[{data:students},{data:teachers}]=await Promise.all([supabase.from('students').select('id,student_id'),supabase.from('teachers').select('id,teacher_id')]);const sm=new Map((students||[]).map(x=>[x.student_id,x.id])),tm=new Map((teachers||[]).map(x=>[x.teacher_id,x.id]));for(const item of list){const personId=item.kind==='student'?sm.get(item.id):tm.get(item.id);if(!personId)continue;const{error}=await supabase.rpc('record_attendance',{person_id:personId,person_type:item.kind,scanned_token:item.id});if(error&&!String(error.message||'').toLowerCase().includes('already_marked_today'))console.error('Attendance sync failed',error);}}
let syncing=false;async function syncPatch(patch){if(!supabaseConfigured||syncing)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;syncing=true;try{if(patch.students)await syncStudents(patch.students);if(patch.teachers)await syncTeachers(patch.teachers);if(patch.attendance)await syncAttendance(patch.attendance);}finally{syncing=false;}}
export async function initDatabaseBridge(){if(!supabaseConfigured)return{connected:false,authenticated:false};const connected=await loadDatabase(),originalSetItem=window.localStorage.setItem.bind(window.localStorage);window.localStorage.setItem=function setItem(key,value){originalSetItem(key,value);if(key===STORAGE&&!syncing){try{void syncPatch(JSON.parse(value));}catch{}}};supabase.auth.onAuthStateChange(async(event,session)=>{if(session)void loadDatabase();if(event==='SIGNED_OUT')originalSetItem(STORAGE,JSON.stringify({students:[],teachers:[],attendance:[],exams:[],results:[],timetable:[],notices:[],homework:[],printed:[]}));});return{connected:true,authenticated:connected};}