import { supabase } from './lib/supabase.js';

(() => {
  const ID='tnps-feedback-widget'; if(document.getElementById(ID)) return;
  const style=document.createElement('style');style.textContent=`#${ID}{position:fixed;right:0;top:45%;z-index:19000;font-family:DM Sans,system-ui,sans-serif}#${ID} .tab{width:50px;height:50px;border:0;border-radius:16px 0 0 16px;background:#6d62e8;color:#fff;display:grid;place-items:center;cursor:pointer;box-shadow:0 10px 28px rgba(70,60,160,.25)}#${ID}.peek .tab{transform:translateX(-7px)}#${ID} .popup{position:absolute;right:10px;top:58px;width:330px;background:#fff;border:1px solid #e8eaf0;border-radius:18px;padding:18px;box-shadow:0 20px 60px rgba(25,30,50,.2);display:none}#${ID}.open .popup{display:block}#${ID} h3{margin:0;font-size:16px}#${ID} .sub{margin:5px 0 14px;color:#7d8799;font-size:11px}#${ID} .actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}#${ID} .actions button{border:1px solid #e8eaf0;background:#fafaff;border-radius:10px;padding:10px 8px;font-size:11px;font-weight:700;cursor:pointer;color:#4f5970}#${ID} .close{position:absolute;right:10px;top:8px;border:0;background:none;font-size:20px;color:#9aa1b0;cursor:pointer}#${ID} .form{display:none}#${ID}.form-mode .actions{display:none}#${ID}.form-mode .form{display:block}#${ID} input,#${ID} textarea,#${ID} select{width:100%;border:1px solid #e2e5ec;border-radius:10px;padding:10px;margin:6px 0 9px;font:inherit;font-size:12px;box-sizing:border-box}#${ID} textarea{min-height:100px;resize:vertical}#${ID} .submit{width:100%;border:0;border-radius:10px;padding:11px;background:#6d62e8;color:#fff;font-weight:800;cursor:pointer}.msg{font-size:11px;margin-top:8px}.ok{color:#25804a}.err{color:#b33a3a}@media(max-width:600px){#${ID} .popup{width:280px;right:8px}}`;document.head.appendChild(style);
  const el=document.createElement('div');el.id=ID;el.innerHTML=`<button class="tab" aria-label="Feedback & Support" title="Feedback & Support"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.7 9.7 0 0 1-4-.9L3 21l1.9-4A8.5 8.5 0 1 1 21 11.5Z"/><path d="M8 12h.01M12 12h.01M16 12h.01"/></svg></button><div class="popup"><button class="close">×</button><h3>Feedback & Support</h3><div class="sub">Report a problem or send feedback. Your ticket goes to the Developer.</div><div class="actions"><button data-type="bug">🐞 Report Bug</button><button data-type="technical">🛠 Technical Problem</button><button data-type="data">📊 Data Issue</button><button data-type="help">❓ Get Help</button><button data-type="feature">💡 Feature Request</button><button data-type="tickets">🎫 My Tickets</button></div><div class="form"><label style="font-size:11px;font-weight:700">Category</label><select id="tnps-ticket-category"><option value="bug">Bug</option><option value="technical">Technical Problem</option><option value="data">Data Issue</option><option value="help">Help</option><option value="feature">Feature Request</option></select><input id="tnps-ticket-title" placeholder="Short title"/><textarea id="tnps-ticket-desc" placeholder="Describe what happened..."></textarea><button class="submit">Submit Ticket</button><div class="msg"></div></div></div>`;document.body.appendChild(el);
  const tab=el.querySelector('.tab');let timer;
  const peek=()=>{if(!el.classList.contains('open')){el.classList.add('peek');clearTimeout(timer);timer=setTimeout(()=>el.classList.remove('peek'),2200)}};setTimeout(peek,2500);setInterval(peek,12000);
  tab.onclick=()=>{el.classList.toggle('open');el.classList.remove('peek')};el.querySelector('.close').onclick=()=>el.classList.remove('open','form-mode');
  el.querySelectorAll('[data-type]').forEach(b=>b.onclick=async()=>{const type=b.dataset.type;if(type==='tickets'){const {data,error}=await supabase.from('tickets').select('ticket_number,title,status,priority,created_at').order('created_at',{ascending:false}).limit(10);const actions=el.querySelector('.actions');actions.innerHTML=error?'<div style="font-size:12px;color:#b33a3a">Unable to load tickets.</div>':(data?.length?data.map(x=>`<button disabled style="text-align:left"><b>${x.ticket_number}</b><br>${x.title}<br><small>${x.status} · ${x.priority}</small></button>`).join(''):'<div style="font-size:12px;color:#7d8799">No tickets yet.</div>');el.querySelector('.sub').textContent='Your recent tickets';return}el.classList.add('form-mode');el.querySelector('#tnps-ticket-category').value=type});
  el.querySelector('.submit').onclick=async()=>{const msg=el.querySelector('.msg'),category=el.querySelector('#tnps-ticket-category').value,title=el.querySelector('#tnps-ticket-title').value.trim(),description=el.querySelector('#tnps-ticket-desc').value.trim();if(!title||!description){msg.className='msg err';msg.textContent='Title and description are required.';return}const {data:{user}}=await supabase.auth.getUser();if(!user){msg.className='msg err';msg.textContent='Please sign in first.';return}const {error}=await supabase.from('tickets').insert({created_by:user.id,title,description,category,page_context:location.pathname,module_context:document.title,browser_context:navigator.userAgent});if(error){msg.className='msg err';msg.textContent=error.message;return}msg.className='msg ok';msg.textContent='Ticket submitted successfully.';el.querySelector('#tnps-ticket-title').value='';el.querySelector('#tnps-ticket-desc').value='';setTimeout(()=>el.classList.remove('open','form-mode'),1300)};
  let dragging=false,moved=false,startY=0,startTop=0;tab.addEventListener('pointerdown',e=>{dragging=true;moved=false;startY=e.clientY;startTop=el.getBoundingClientRect().top;tab.setPointerCapture(e.pointerId)});tab.addEventListener('pointermove',e=>{if(!dragging)return;const dy=e.clientY-startY;if(Math.abs(dy)>4)moved=true;el.style.top=Math.max(12,Math.min(innerHeight-62,startTop+dy))+'px'});tab.addEventListener('pointerup',e=>{dragging=false;try{tab.releasePointerCapture(e.pointerId)}catch{}if(moved){setTimeout(()=>moved=false,0)}});
})();
